In [15]:
import pandas as pd
import numpy as np

data = pd.read_excel("distancedataess.xlsx",header=None)
list = data.values.tolist()
distance_metric = np.array(list)
print(distance_metric)
city = len(data)
print(city)

[[ 0.  10.  15.  20.  37.5 12.  16.  20.  26.9 40.  20.2 22.  25.  28.
  32.  36.  38.  39.  40.7 45. ]
 [10.   0.   7.5 17.5 27.5 18.  11.2 12.5 18.  26.9 23.6 20.2 20.6 26.6
  36.1 31.6 30.  30.9 34.7 40.7]
 [15.   7.5  0.  10.  20.  21.  18.  10.  12.5 16.  28.3 25.  20.2 23.
  26.  27.  28.  30.  31.6 35. ]
 [20.  17.5 10.   0.  10.  23.  22.  19.  10.3 15.  36.1 34.  23.6 22.
  26.  32.  34.  32.  30.  31. ]
 [37.5 27.5 20.  10.   0.  43.7 34.  22.4 16.  10.3 44.7 36.1 30.1 22.4
  20.2 48.  40.7 36.1 31.6 30. ]
 [12.  18.  21.  23.  43.7  0.  10.  20.  30.  40.  10.3 12.  22.4 25.
  30.  21.  24.  28.  38.2 40. ]
 [16.  11.2 18.  22.  34.  10.   0.  10.  20.  30.  12.5 13.  14.1 16.
  18.  22.  25.  28.  30.1 35. ]
 [20.  12.5 10.  19.  22.4 20.  10.   0.   7.5 15.  22.4 18.  10.3 13.
  15.  28.  25.  21.  22.4 25. ]
 [26.9 18.  12.5 10.3 16.  30.  20.   7.5  0.  10.  29.3 20.2 14.1 10.3
  18.  32.  25.  21.4 20.2 23.6]
 [40.  26.9 16.  15.  10.3 40.  30.  15.  10.   0.  38.8 34. 

In [30]:
serve_center = 4
serve_position = np.array([1,8,12,18])
#chrome = np.zeros((serve_center,city),dtype=int)
#for i in range(city):
ch = []
chrome = np.zeros((serve_center,city),dtype=int)

serve_position = serve_position.tolist()
print(chrome)
m,n = chrome.shape
print(m)
print(n)
k = 0
def q(q, serve_position):
    result = 0
    for f in serve_position:
        if q == f:
            result = 1
    return result

for i in range(city):
    if q(i, serve_position) == 1:
        chrome[k][i] = 1
        k = k+1
    else:               
        j = np.random.choice(serve_center)
        chrome[j][i] = 1
print(chrome)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
4
20
[[0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 1]]


In [3]:
data_nb = pd.read_excel("adjacentdata.xlsx",header=None)       
list_nb = data_nb.values.tolist()
neighbor_metric = np.array(list_nb)
'''
c = np.matmul(chrome, neighbor_metric)
cc = np.multiply(c,chrome)
a = 0
for i in range(m):
    for j in range(n):
        if cc[i][j] == 1:
            a = a-1
print(a)
'''

'\nc = np.matmul(chrome, neighbor_metric)\ncc = np.multiply(c,chrome)\na = 0\nfor i in range(m):\n    for j in range(n):\n        if cc[i][j] == 1:\n            a = a-1\nprint(a)\n'

In [4]:
# 邻接矩阵约束
def neighbor(ch, neighbor_m):
    x = ch.copy()
    a = neighbor_m.copy()
    c = np.matmul(x, a)
    cc = np.multiply(c,x)
    k = 0
    for i in range(m):
        for j in range(n):
            if cc[i][j] == 1:
                k = k-1
    return k

print(neighbor(chrome, neighbor_metric))            
    

        

0


In [13]:
def repeat(solutions, solutions_list):
    solutions_l = np.array(solutions_list)
    b = 0
    for i in range(len(solutions_list)):
        if ((solutions == solutions_l[i]).all()) == True and len(solutions_l[i]) != 20:
            b = 1
    return b           


def init_solutions(city, serve_position, neighbor_metric):
    k = 0
    
    solutions_list = []
    while k < 20:
        a = 0
        solutions = np.zeros((len(serve_position),city),dtype=int)
        for i in range(city):
            if i == 1 or i == 8 or i == 12 or i==18:# i == 1 or i == 8 or i == 12 or i==18
                solutions[a][i] = 1
                a = a+1
            else:               
                j = np.random.choice(serve_center)
                solutions[j][i] = 1
        if neighbor(solutions, neighbor_metric) == 0 and repeat(solutions, solutions_list) == 0:
            k = k + 1
            solutions_list.append(solutions)
    return solutions_list
solutions_list = init_solutions(city, serve_position, neighbor_metric)
print(solutions_list)


1
[array([[0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]]), array([[1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0]]), array([[0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]]), array([[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0,